import type {Metadata} from "next";
import {Lato, Roboto} from "next/font/google";
import "@/styles/globals.scss";

const roboto = Roboto({
    variable: "--font-roboto",
    weight: ["100", "300", "400", "700", "900"],
    subsets: ["latin", "cyrillic"],
});
const lato = Lato({
    variable: "--font-lato",
    weight: ["100", "300", "400", "700", "900"],
    subsets: ["latin","latin-ext"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout(
    {
        children,
    }: Readonly<{
        children: React.ReactNode;
    }>
) {
    return (
        <html lang="en">
        <body
            className={`${lato.variable} ${roboto.variable} antialiased`}
        >
        {children}
        </body>
        </html>
    );
}
